-- users table
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  fullname VARCHAR(255) NOT NULL,
  avatar VARCHAR(500) NOT NULL,
  coverimage VARCHAR(500),
  refreshToken TEXT,
  password VARCHAR(255) NOT NULL,
  otp VARCHAR(255),
  otp_expiry DATETIME,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
-- watch history table
CREATE TABLE IF NOT EXISTS watch_history (
  user_id INT NOT NULL,
  video_id INT NOT NULL,
  watched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, video_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE
);
-- tweet table
CREATE TABLE IF NOT EXISTS tweets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  owner INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (owner) REFERENCES users(id) ON DELETE CASCADE
);
-- videos table
CREATE TABLE IF NOT EXISTS videos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  video VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  duration INT NOT NULL,
  views INT DEFAULT 0,
  is_published BOOLEAN DEFAULT TRUE,
  owner INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (owner) REFERENCES users(id) ON DELETE CASCADE
);
-- comment table
CREATE TABLE IF NOT EXISTS comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  video INT NOT NULL,
  owner INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (video) REFERENCES videos(id) ON DELETE CASCADE,
  FOREIGN KEY (owner) REFERENCES users(id) ON DELETE CASCADE
);
-- like table
CREATE TABLE IF NOT EXISTS likes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  video INT DEFAULT NULL,
  comment INT DEFAULT NULL,
  tweet INT DEFAULT NULL,
  liked_by INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (video) REFERENCES videos(id) ON DELETE CASCADE,
  FOREIGN KEY (comment) REFERENCES comments(id) ON DELETE CASCADE,
  FOREIGN KEY (tweet) REFERENCES tweets(id) ON DELETE CASCADE,
  FOREIGN KEY (liked_by) REFERENCES users(id) ON DELETE CASCADE
);
-- subscription table
CREATE TABLE IF NOT EXISTS subscriptions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  subscriber INT NOT NULL,
  channel INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (subscriber) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (channel) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE (subscriber, channel)
);
-- playlist table
CREATE TABLE IF NOT EXISTS playlists (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  owner INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (owner) REFERENCES users(id) ON DELETE CASCADE
);
-- playlist_videos table
CREATE TABLE IF NOT EXISTS playlist_videos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  playlist INT NOT NULL,
  video INT NOT NULL,
  FOREIGN KEY (playlist) REFERENCES playlists(id) ON DELETE CASCADE,
  FOREIGN KEY (video) REFERENCES videos(id) ON DELETE CASCADE,
  UNIQUE (playlist, video)
);